### ISSUE TITLE
Encoding differences between user input and filesystem resources 

### ISSUE THREAD

**Issue by amazeika** [timble/kodekit-platform#63]
Migrate code changes from: https://github.com/joomlatools/joomlatools-framework-files/issues/10

**Comment by amazeika** [comment]
@johanjanssens Assigned to you for testing. This will simply set the entity name property to match the encoding that got used while creating the folder. We do this so that the POST response contains the good folder name which may be used by the client code afterwards.

**Comment by johanjanssens** [comment]
@amazeika Did code review. I suspect that this code was added to com:files for Koowa and is working there?

**Comment by amazeika** [comment]
@johanjanssens Correct. This is working perfectly well and was the culprit to some UI misbehavior when creating folders.

Sorry for the namespace issue, I would have noticed with some testing but I've assigned it to you instead as requested. I'll make the fix tomorrow morning.
