### ISSUE TITLE
Sync activities with latest version

### ISSUE THREAD

**Issue by amazeika** [timble/kodekit-platform#64]
See:

https://github.com/joomlatools/joomlatools-framework-activities/issues/1
https://github.com/joomlatools/joomlatools-framework-activities/issues/8
https://github.com/joomlatools/joomlatools-framework-activities/issues/10

Note:

Also go through all commits on repo since last release.

**Comment by johanjanssens** [comment]
@amazeika Can you put this on your todo for the coming weeks?

**Comment by amazeika** [comment]
@johanjanssens will do.
